### ISSUE TITLE
Error 404 for SysML v2 implementation

### ISSUE THREAD

**Issue by theogiraudet** [MontiCore/monticore.github.io#1] opened 2022-12-12 16:57 UTC
Hello, 
I see on the [website](https://monticore.github.io/monticore/docs/Languages/) that Monticore can support SysML v2 (in alpha) but the link to the git project goes to a 404 error. Is this support discontinued or is it just a forgotten update to the website?

Thanks!

**Comment by N-Jansen** [comment] 2022-12-16 09:05
Dear Theo,

thank you for reporting this issue. We are working on it. Generally, our SysML v2 realization was intended to be still private (as it is still in an alpha version). However, the broken link is definitely an error.

Best regards,
Nico

**Comment by theogiraudet** [comment] 2022-12-16 09:23
Thanks for your answer. I was just curious about your implementation of this language, but no problem if the project is private for now!

**Comment by N-Jansen** [comment] 2022-12-21 09:49
Links of private projects are now marked as internal.

**Closed as completed by N-Jansen** 2022-12-21 09:49 UTC
